version: "3"

services:
  jenkins:
    build:
      context: ./dockerfiles/${APPLICATION}
    container_name: "${COMPOSE_PROJECT_NAME}-${APPLICATION}"
    restart: "always"

    privileged: true

    ports:
      - "${HOST_MACHINE_APP_PORT}:8080"
    volumes:
      - ${JENKINS_DATA_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    links:
      - database
    networks:
      - jenkins_network

networks:
  jenkins_network:
    ipam:
      config:
        - subnet: ${SUBNET_CIDR}